parameters:
    notify_mailer.class: OpenSkedge\AppBundle\Mailer\Mailer

services:
    notify_mailer:
        class: %notify_mailer.class%
        arguments: [@mailer, @twig, @logger, { senderEmail: %sender_email%, appname: %app_name% }]
    request:
        class: Symfony\Component\HttpFoundation\Request
    page.twig.extension:
        class: OpenSkedge\AppBundle\Twig\Extension\PageExtension
        arguments:  [@request]
        tags:
            - { name: 'twig.extension' }
