parameters:
#    openskedge.example.class: OpenSkedge\AppBundle\Example

services:
#    openskedge.example:
#        class: %openskedge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    request:
        class: Symfony\Component\HttpFoundation\Request

    openskedge.twig.extension:
        class: OpenSkedge\AppBundle\Twig\Extension\PageExtension
        arguments:  [@request]
        tags:
            - { name: 'twig.extension' }

